env:
  browser: false
  es2021: true
root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: tsconfig.eslint.json
plugins:
  - "@typescript-eslint"
rules:
  no-console: "warn"
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }]
  "@typescript-eslint/no-floating-promises": "error"
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
